version: '3.8'
services:
  db:
   image: postgres:15
   environment:
    POSTGRES_USER: ${POSTGRES_USER}
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    POSTGRES_DB: ${POSTGRES_DB}
   ports:
    - "5432:5432"
   volumes:
    - pgdata:/var/lib/postgresql/data


  n8n:
    image: n8nio/n8n:1.75.0
    depends_on:
      - db
    environment:
    - DB_POSTGRESDB_HOST=db
    - DB_POSTGRESDB_PORT=${POSTGRES_PORT}
    - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
    - DB_POSTGRESDB_USER=${POSTGRES_USER}
    - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
    - N8N_BASIC_AUTH_ACTIVE=${N8N_BASIC_AUTH_ACTIVE}
    - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
    - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
    - N8N_HOST=${N8N_HOST}
    - N8N_PROTOCOL=${N8N_PROTOCOL}
    - N8N_PORT=${N8N_PORT}
    - GOOGLE_TRENDS_PROXY_URL=${GOOGLE_TRENDS_PROXY_URL}
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n


  metabase:
   image: metabase/metabase:v0.49.12
   ports:
    - "3000:3000"
   environment:
    - MB_DB_FILE=${MB_DB_FILE}
   volumes:
     - mbdata:/metabase-data


volumes:
  pgdata:
  n8n_data:
  mbdata: